services:
  - type: web
    name: psu-dorm-finder
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm ci --only=production
      npm run build
    startCommand: |
      php artisan migrate --force
      php artisan storage:link
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://psu-dorm-finder.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: NOCAPTCHA_SITEKEY
        value: 6LdontgrAAAAADF6Wl923X1kXTDVBZdBU5oFHImD
      - key: NOCAPTCHA_SECRET
        value: 6LdontgrAAAAACkN0f77aL7bOsGo1PfcAFFHxs3N

databases:
  - name: psu-dorm-finder-db
    plan: free